### ISSUE TITLE
🌂傘コンポーネントを汎用的なものに変更する🌂

### ISSUE THREAD

**Issue by azukisiromochi** [harape5peanuts/portfolio#2]
## :mount_fuji: 背景
現在の傘🌂コンポーネントは、色を変えることができず、たくさんのカラフルな傘🌂を散りばめるという仕様を実現できそうにない.

## :warning: 問題点
傘🌂の部分が `<img>` タグになっており、 `<svg>` として扱うことが出来ない状況.

## :memo:  再現方法
特になし.

## :mortar_board: 解決策 / 解決案
傘🌂の部分を SVG パスとして作成することが必要になる.
慣れない作業で大変だと思うけどファイトな！ :bow:

**Comment by harape5peanuts** [comment]
傘を `<img>` タグから `<svg>` タグに変更しましたのでクローズします。
